### ISSUE TITLE
Why is this based on XSD usage?

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/iregexp#15]
I have concerns that this spec being [based on XSD-2](https://www.ietf.org/archive/id/draft-ietf-jsonpath-iregexp-02.html#section-4) may not be suitable for JSON Path, as was the original intent.

Primarily, XSD is an XML technology, while JSON Path is a JSON technology.  While the argument _could_ be made that JSON Path is the JSON analogy for XPath, it doesn't follow that all the conventions must come with it.  This specification should, at a minimum, follow the conventions and expectations already established by the JSON development community.  It follows that, if anything, the basis for this specification should be ECMA-262 from ECMAScript, a.k.a. Javascript, from which JSON is derived.

Secondarily, the feature set in XSD is not representative of the majority of implementations (e.g. implicit anchoring).  The original intent for this specification was interoperability, and in that interest, it seems more appropriate for this specification to define the intersection of features amongst the most common and popular regular expression dialect.  Instead, it takes one dialect (which arguably is less common and less well-known) as the basis and providing conversion instructions to the more common ones.  This practice seems antithetical to the goal of interoperability.

**Comment by timbray** [comment]
I speak as someone who is on the record as loathing XSD generally.  But I'm supportive of borrowing that regexp idiom because (a) it has a stable immutable specification and (b) it looks to me like an attractively sized clean subset of the other well-known flavors.  Implicit anchoring is easy to understand and doesn't feel like a problem - are there any other significant ways in which this flavor is not representative?

**Comment by gregsdennis** [comment]
The genesis of this spec (through conversations in JSON Path interim meetings) was dissatisfaction with the current variability of existing dialects and the desire to support a dialect that was interoperable

To achieve this, we should have surveyed existing dialects for features and independently defined the intersection of those features here.  But there is no evidence that this was done.  Instead, XSD seems to have been arbitrarily chosen as a basis (and implicit anchors along with it).

We SHOULD NOT be assuming one (any one) dialect as a basis.  We should be defining our own _based on_ common usage in the community.

There has been no evidential argument presented as to why XSD should be a basis for this spec nor that the XSD dialect is still commonly used.  To the contrary, I present these online evaluators, which were the top 5 results of a Google search:

- https://regex101.com/
- https://regexr.com/
- https://www.regextester.com/
- https://www.freeformatter.com/regex-tester.html
- https://www.debuggex.com/

Many of these sites even offer different language-based rulesets so that different dialect behaviors can be compared.  Even an [online grep](https://www.online-utility.org/text/grep.jsp) agrees with their behavior.

I expect the intersection of the features provided by these sites very closely matches the ABNF present in the spec.  However, none of these support implicit anchoring as their default behavior.

The evidence shows that implicit anchoring would be an unexpected behavior for developers, which is a bad experience.  To best encourage adoption of JSON Path (and even I-Regexp in general by other specifications, like JSON Schema), common, well-known behaviors need to be included, and less common, unsupported behaviors need to be excluded.

Lastly, with implicit anchoring enabled, how does one explicitly _exclude_ anchors?

**Comment by timbray** [comment]
The reason we based this on XSD is because it has a freely available, immutable specification that other people wrote so we don't have to, and that its features are an attractive subset of many existing dialects.  I do not have sufficient spare time to engage in recreating specifications that other people have already written.

I agree that a variety of different approaches to this work would produce pretty well the same ABNF, and if you're aware of another such spec that has the same advantages but is preferable for some reason, I'd have no objection to switching.

I haven't seen any data that establishes that either anchored or unanchored regexps are more generally useful. 

> Lastly, with implicit anchoring enabled, how does one explicitly _exclude_ anchors?

As it says in [the XSD regexp spec](https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#regexs): "including .* at the beginning and ending of the regular expression will achieve the desired results"

**Comment by gregsdennis** [comment]
> I do not have sufficient spare time to engage in recreating specifications that other people have already written.

But that's exactly what we're doing!  We're not referencing XSD and saying, "This spec does the same as XSD except..." We're completely redefining the behavior, starting by _copying_ from what's in XSD.  That means we can change it where we feel it falls short.

> I haven't seen any data that establishes that either anchored or unanchored regexps are more generally useful.

I'm not saying one or the other is more or less _useful_.  I'm saying that implicit anchoring is less _common_.  The majority of developers expect a regex engine to require explicit anchors because this is the behavior that modern implementations employ. 
 Implicit anchoring is a significant gotcha that will cause many people to encounter unexpected behavior as they work with JSON Path.

I believe basing this on XSD (and holding fast to that basis) is unreasonable.  Regardless of whether XSD stable, it's a lesser known dialect, and I fear that will inevitably hurt JSON Path.

**Comment by handrews** [comment]
> I haven't seen any data that establishes that either anchored or unanchored regexps are more generally useful.

It's not about what's "more generally useful", it's about what fits the target ecosystem.  If this is supposed to benefit JSON-based projects, that is an ECMA-based world, not an XML-based one.  And ECMA, as well as most of the most popular relevant programming languages including JavaScript, Java, Python, Perl, Ruby, C++ and even current hot language Rust all either have entirely unanchored regexes or have different functions/methods that impose different anchor behavior on regexes that are written as unanchored.  In all cases, the expectation is that the regex as written is unanchored, even if the desired usage is anchored on both ends.

**Comment by glyn** [comment]
On regexp anchoring, http://www.rexegg.com/regex-anchors.html is both
informative and disturbing. It seems the semantics of ^ and $ vary between
regexp implementations and so cannot be taken for granted.

This example raises an interesting question: https://regex101.com/r/fQGLTr/1
- the regexp implementations there give two matches of e$ in the string
"one\napple\n". Does the XSD-2 regexp .*e match against that string? That
is, does its implicit anchoring ignore trailing newlines?

The spec appears to be silent about this and some aspects of so-called
"multiline mode" (see the regex101 link above). I presume XSD-2 regexp
anchoring operates like some other regexp implementations when multiline
mode is off, but it's hard to be sure from the spec.

**Comment by cabo** [comment]
> On regexp anchoring, http://www.rexegg.com/regex-anchors.html is both informative and disturbing. It seems the semantics of ^ and $ vary between regexp implementations and so cannot be taken for granted. 

Indeed.  That was an additional reason not to use explicit anchors in iregexp (the main reasons are that an anchored string is actually what is desired in the vast majority of the use cases, and that it is too easy to use anchors in the wrong way).

> This example raises an interesting question: https://regex101.com/r/fQGLTr/1 - the regexp implementations there give two matches of e$ in the string "one\napple\n". 

Yes, a sliding regexp with the usual (non-JS) semantics of `$` will match all `e` characters that are at the end of lines.

> Does the XSD-2 regexp .*e match against that string? 

No, as the string does not end with `e`.
(There also is the problem that .* does not match newlines, so `(.|[^x])*` or some such needs to be used for a 2d [multiline] match.  Stupidly, XSD does not support [^], but that would not be interoperable with other implementations anyway.)

> That is, does its implicit anchoring ignore trailing newlines? The spec appears to be silent about this and some aspects of so-called "multiline mode" (see the regex101 link above). 

It is silent because XSD doesn't do anything extra here.
(Functionality not described is to be assumed to be not there.)

> I presume XSD-2 regexp anchoring operates like some other regexp implementations when multiline mode is off, but it's hard to be sure from the spec.

iregexp currently does not provide a way to attach a "mode" to a regexp.
"mode"s are probably the most non-interoperable part of the regexp zoo, so I'm not sure that this should be added -- it would most certainly need translation when transforming into an existing implementation.

**Comment by handrews** [comment]
@cabo 

> Indeed. That was an additional reason not to use explicit anchors in iregexp (the main reasons are that an anchored string is actually what is desired in the vast majority of the use cases, and that it is too easy to use anchors in the wrong way).

You keep making this claim but I see no evidence of it.  The XSD spec says something like this, but _only_ in the context of their specific `pattern` attribute.

I spent many years as a technical lead for test automation, where I inherited a large Perl automation system for CLI testing which was used by multiple teams across a product line.  It relied heavily on matching using regexes, and anchored regexes were _not_ what was desired in the vast majority of cases.

It's also worth noting that over the past six or so years of JSON Schema work, while occasionally people ask about anchoring or want it clarified in the spec (for some reason that bit of information has migrated around the documents over time), there has never been anything remotely resembling a significant or steady demand for anchored regexes.

**Comment by timbray** [comment]
Let me pick apart the arguments here in an effort to help us achieve consensus. I think there are three distinct issues here; I'll list them and maybe it would be more productive to separate them out into separate issues?  

1. Rather than adopting someone else's regular expression specification, we should write our own from scratch based on a survey of the overlap between popular idioms. 
2. If we are going to base I-Regexp on another regexp specification, it shouldn't be XSD's, because that is XML-tainted and not ECMA-flavored enough. We should base on X for some value of X. (Comment: Suggestions for X?)
3. IRegexps should not be anchored by default. (Comment: This could be fixed by amendment to the current draft I think?)

Do we agree on what we're arguing about?

**Comment by handrews** [comment]
@timbray thanks for laying this out.  For me, I'm arguing points 2 and 3.  I have no strong opinion on point 1, although I tend to lean towards adopting an existing dialect _if_ it is otherwise suitable.

Point 2 is less about being "XML-tainted" and more about XML not aligning with ECMA world and ECMA world being more relevant.  We cite XML sources for JSON Schema where it makes sense, for example when aligning plain-name fragment syntax.  For our referencing and identification discussion, I filed an issue to take a look at XML Include for inspiration and, if relevant, compatibility.

The concern here is that the ECMA dialect is more relevant and familiar for JSON-based usage.  Perhaps there needs to be a more thorough explanation of IRegexp's target audience before the relevance can truly be assessed.

Regarding Point 3, yes, "XSD but not implicitly anchored" could be a path forwards.  If I were considering that for JSON Schema (and to be clear, what happens there is not my person decision), I'd look and see how often and in what circumstances I'd need to process such regexps before I could use them in my environment.  This is where question of likely programming languages and libraries should also be considered.  If the majority of such languages and libraries assume _explicit_ anchoring only, that means a lot of little bits of processing code have to be inserted all over the place, which introduces a lot of opportunity for error.

**Comment by cabo** [comment]
> 3\. IRegexps should not be anchored by default. (Comment: This could be fixed by amendment to the current draft I think?)

Explicit anchors means that we need to define their semantics, work I haven't done so far because I consider it pointless.  (Compare Glyn's example above why this is not trivial.)

JSONPath provides for delimiting strings with single quotes.  Given the arguments here, I don't understand why that isn't at least as bad as implicitly anchoring regexps.

**Comment by timbray** [comment]
I am also a bit concerned by the occasionally slippery interaction between anchoring and behavior around embedded \n and \r.

My preference would probably be to stay with the current anchored behavior but I could be persuaded by concrete data supporting the proposition that unanchored would be more useful.

**Comment by timbray** [comment]
> Point 2 is less about being "XML-tainted" and more about XML not aligning with ECMA world and ECMA world being more relevant. We cite XML sources for JSON Schema where it makes sense, for example when aligning plain-name fragment syntax. For our referencing and identification discussion, I filed an issue to take a look at XML Include for inspiration and, if relevant, compatibility.

Hmm, I just went and re-read the XSD definition and it's generally OK.  Specifying regexp syntax/semantics is really non-trivial and someone has put in a lot of work here. Once again, I'd be happy with a better alternative, but to date nobody has proposed one.

**Comment by timbray** [comment]
With my co-chair hat on, which always means I'm looking for a path to consensus, I'm going to suggest that the only really outstanding issue is on anchored-or-not.  We know what @cabo, @handrews, and @gregsdennis think (My co-chair-hat-off position is not strongly held enough to be interesting).  Any other voices?

**Comment by cabo** [comment]
It would be good to have a corpus of actual regexp uses in JSONPath -- not made-up examples, but actual use.
The question I'm interested is not whether these have explicit anchors, but whether sliding regexps are used much in JSONPath.

**Comment by handrews** [comment]
@timbray I second the call for other voices, and i want to raise a sincere question about how we are measuring the concept of "useful".  The interoperability of `^` and `$` is a valid concern, but what do we weigh that against?

While @cabo 's question of what is used in JSON Path is certainly relevant, it again raises the question of the target audience of this specification.  It is impossible to evaluate "usefulness" without understanding the audience.  And not just their needs in terms of functionality, but their likely assumptions.

We've already [established](https://github.com/ietf-wg-jsonpath/iregexp/issues/15#issuecomment-1291175987) that a lot of very popular programming languages either _require_ unanchored regexps, or require that you choose a different function/method or otherwise configure something to get implicit anchoring on one or both ends.  Most people will assume regexps work the way they are used to.  XSD-oriented folks will expect implicit anchoring, but who know regexps from their usual programming languages will not.

The next question should be:  What would the translations look like for an interoperable non-implicitly-anchored regexps?  Particularly ones using `^`, `$`, and those where `\n` or `\r` appear in the string being matched (@timbray I assume that's what you meant by "embedded"?).

These should be compared to the translations already listed, plus consideration of how to translate those implicitly-anchored XSD-style regexps in the presence of `\n` or `\r`.  I'm not convinced that what is currently present is comprehensive.  For example, I don't see anything that addresses the lack of \\z in Python, which AFAICT should be covered by [§5.4](https://www.ietf.org/archive/id/draft-ietf-jsonpath-iregexp-02.html#section-5.4).  I'm also confused about the lack of mention of multiline mode, given that I don't think you can turn it off in Ruby (perhaps I'm just overlooking the mention in I-Regexp?  The only appearance of "line" near "multi" involve excluding "multi-line constructs" from a set of examples.

**Comment by timbray** [comment]
Like I said, I don't really have much of an opinion about this.  The argument from the way languages do it is real but tbh doesn't seem like that big a deal, assuming the RFC is nice and clear. Anyone who's mature enough to have coded in >1 programming language is going to be smart enough to check the reference. Like Carsten says, it'd be nice to have a corpus to look at, but I don't think that's gonna happen.

But, I do agree that the spec probably needs to proactively highlight the anchoring issue, including a discussion of multiline - because no matter which we pick, some subset of users are going to be surprised.

Another fact that's in my mind, not sure if it helps choose though. If we choose anchored mode, then you use `.*` at the beginning and end to un-anchor. If you choose un-anchored, then you have to use `^` and `$` to anchor. Neither is really much of an irritant?

In any case, I'm pretty convinced that when we make a consensus call, the penalty for being wrong will be pretty mild.

**Comment by timbray** [comment]
> While @cabo 's question of what is used in JSON Path is certainly relevant, it again raises the question of the target audience of this specification. It is impossible to evaluate "usefulness" without understanding the audience. And not just their needs in terms of functionality, but their likely assumptions.

I think trying to characterize the target audience is probably not useful, because regexp is about as low-level and horizontal a programming technology as exists.  The only reasonable answer is "anyone who wants boolean matches against strings" which rounds to "more or less anyone doing more or less anything".  If someone wants to propose a characterization, go ahead, but I'm dubious.

**Comment by handrews** [comment]
> If we choose anchored mode, then you use `.*` at the beginning and end to un-anchor.

I'm pretty sure you need the non-greedy `.*?` syntax at the beginning.

Regarding audiences, I've gone into some detail about communities, expectations, and assumptions, but apparently none of that is of interest.  And yet @cabo didn't hesitate to [exclude JSON Schema from the audience](https://github.com/json-schema-org/json-schema-spec/issues/1327#issuecomment-1292322839) and [assert a broader intended audience than just JSON Path](https://github.com/json-schema-org/json-schema-spec/issues/1327#issuecomment-1292522683).  So someone here has some concept of what the audience is.

Please note that I am not bothered by JSON Schema's interests being excluded (BTW, I assumed that meant excluding JSON Schema's current usage of regexps in `pattern` and `patternProperties`, not that there was a desire to prevent I-Regexp from being useful for some aspect of JSON Schema somewhere).  That is not a problem and does not require a "solution."  But if we're going to strike down arguments in favor of something because the person/project making them is not part of the target audience... well, it would be a lot easier to figure out what's going on here if we had more to go on than "more than JSON Path, but not JSON Schema."

I proposed some heuristics, and I honestly have no idea what conclusion those heuristics would produce.  It wasn't an attempt to get a specific outcome.  It was an attempt to get beyond "people A, B, and C like implicit anchoring, and people X, Y, and Z do not".  Arguing by opinion just means that whoever is in control will probably put in their opinion (that's not a criticism, I've done it myself b/c sometimes you have to pick _something_  and "whoever is doing the work" is not the worst criteria).

**Comment by glyn** [comment]
Checking the JSONPath comparison project, there is no consensus in the regexp tests, but it seems that most implementations that support regexps reasonably do not support implicit anchoring (see the results of [this test](https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_regular_expression.html)).

In terms of JSONPath's use of i-Regexp, I think we need to call out implicit anchoring in the JSONPath spec. But there would still remain the surprise factor for users (who haven't read the spec, probably the majority) when migrating queries that require no implicit anchoring to a JSONPath implementation.

**Comment by cabo** [comment]
One way to maybe prepare for that surprise would be to use a different operator than `=~`

**Comment by glyn** [comment]
If we jettison `=~`, it would be tempting to defer regexp support to extension points so implementers and users can pick their preferred regexp semantics:

* iregexp_match(..., regexp)
* regexp2_match(..., regexp)
* etc.

**Comment by gregsdennis** [comment]
> see the results of this test

That test is invalid for arguing about anchoring because it only works for implementations that support `=~`, which many do not.  (Granted, regex is useless/invalid without that operator.)

**Comment by cabo** [comment]
> * iregexp_match(..., regexp)

This may be what we'll do if we can't find consensus.

Splitting up the ecosystem would be a terrible outcome.
So I'd rather try for a single (~ preferred) solution -- of course, alternatives can be registered at any time.

**Comment by handrews** [comment]
> * iregexp_match(..., regexp)
> * regexp2_match(..., regexp)

This would be a little like what Python and C++ do.  Both have a `match()` and a `search()`.  In both, `search()` is unanchored.  In Python, `match()` implicitly anchors the beginning but not the end, while in C++ `match()` implicitly anchors both ends.  So whether the different functions are standardized or extensions, offering two with different anchoring semantics, particularly if `search()` is the unanchored one, would be less surprising.

Having come here from the JSON Schema issue rather than JSON Path, I did not realize you were planning to use `=~`.

As someone who has worked with Perl way more than I like to think about, I feel ***very*** strongly that if you use Perl's `=~` (which Ruby also borrowed), it really has to be unanchored.  Regular expressions in Perl are _never_ implicitly anchored.  AFAICT the operator is never implicitly anchored in Ruby either.  Making `=~` implicitly anchored would completely contradict the expectations of literally everyone who has ever used it.

But if you offer `match()` and `search()` (or some other pair), people will at least realize they have to choose an anchoring behavior.  You could document the additional interoperability challenges of the unanchored one.

**Comment by glyn** [comment]
I agree about the anchoring semantics of `=~`. It has to be unanchored or JSONPath should ditch `=~`.

Maybe  naming I-Regexp extensions `match()` and/or `search()` and defining such in the JSONPath spec would be a way of minimising any fragmentation of the ecosystem.

Alternatively, if we wanted the benefits of `=~`, the JSONPath spec could define a mapping of an unanchored regexp to I-Regexp. (If some implementations were lucky that mapping composed with the mapping of I-Regexp to the chosen, not implicitly anchored, regexp engine would be simpler than the mapping of I-Regexp to the same engine.)

**Comment by cabo** [comment]
OK, that surely simplifies the grammar.
match(re, s) should be a Boolean function.
I'd say that for search(re, s) as well, but I don't know what people expect.
If there is a choice of which position can match (and people are using that position), suddenly things like greedy vs. non-greedy start to have an influence again, and things become complicated.
Didn't know about the left-anchored semantics in Python!  Do we need that, too?

**Comment by handrews** [comment]
> OK, that surely simplifies the grammar.
> match(re, s) should be a Boolean function.
> I'd say that for search(re, s) as well, but I don't know what people expect.

Yes, in Python both `match()` and `search()` return a match object that is truthy if the regexp matched anything (but can also access capture groups and do other things not relevant here).  They return `None` (which is false-y) on failure.

> If there is a choice of which position can match (and people are using that position), suddenly things like greedy vs. non-greedy start to have an influence again, and things become complicated.

Perl's `=~` and Python's `search()` start matching at the first occurrence.  I believe JavaScript's `search()` (which returns -1 if the search fails and the match position if it succeeds- `test()` is JavaScript's boolean unanchored function) also matches the first occurrence.  JavaScript's `match()` is rather different, which I think just means that there's no cross-language convention for `match()` and defining whatever makes sense should work.  `search()` appears to always be unanchored, with only minor differences in how the return value is handled.

> Didn't know about the left-anchored semantics in Python! Do we need that, too?

I've also written quite a bit of Python and rarely if ever use `match()`.  At some point I led the migration of that very large Perl automation library to Python (not that we replaced everything, but we replaced the core functionality and wrote new automation on that).  `=~` was used heavily in Perl automation, but in Python we tended to use string functions more and regexps less.  I don't know what the stats were for that project (it was was spread across many teams in a large org so I didn't watch every line of code).  Coming from Perl, `search()` felt more natural to the team so we were probably biased against it.

In my own Python work, I only use `match()` if I have a beginning-anchored regex and happen to think the semantics are more clear that way.

Unanchored vs anchored at both ends seems sufficient to me, although I'm sure someone out there loves beginning-anchored.

**Comment by gregsdennis** [comment]
I, too, am happy with the dual-function approach.  It seems that one can be implemented as depending on the other pretty easily.

Are other people happy with removing `=~` and replacing with functions?

(side note: `` `=~` ``</code> is really hard to type)

**Comment by ghost** [comment]
As was discussed at the JSONPath November Interim meeting - anchoring is defined in part within [sections 5.3 and 5.4](https://ietf-wg-jsonpath.github.io/iregexp/draft-ietf-jsonpath-iregexp.html#section-5.3).
